Numpy is a fundamental library for scientific computing in python it provides support for arrays and matrices along with a collections of mathematical functions to operate on these data structure 

In [2]:
!pip install numpy 



Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np 
## Create array using numpy 
## Create a 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)  ## 1 row and 5 column


array([[1, 2, 3, 4, 5]])

In [6]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [7]:
## this is 2d arrays
arr2 = np.array([[1,2,3,4,5] , [2,3,4,5,6]])
print(arr2)
print(arr2.shape)


[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [13]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#attributes of numpy array 
arr = np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr)
print("Shape",arr.shape)
print("Number of dimension" , arr.ndim)
print("Size (Number of elements)", arr.size)
print("Data type", arr.dtype)
print("items size is(in bytes)",arr.itemsize)


Array:
 [[1 2 3]
 [4 5 6]]
Shape (2, 3)
Number of dimension 2
Size (Number of elements) 6
Data type int64
items size is(in bytes) 8


In [5]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])
##Element wise addition 
print("Addition",arr1+arr2)
##Element wise subtraction 
print("Addition",arr2-arr1)
##Element wise multiplication
print("Addition",arr1*arr2)
##Element wise division 
print("Addition",arr1/arr2)


Addition [11 22 33 44 55]
Addition [ 9 18 27 36 45]
Addition [ 10  40  90 160 250]
Addition [0.1 0.1 0.1 0.1 0.1]


In [6]:
##universal Function 
arr = np.array([2,3,4,5,6])
##Square root 
print(np.sqrt(arr))
##Exponential
print(np.exp(arr))
##Sine
print(np.sin(arr))
##natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [14]:
## array slicing and indexing operations 
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
#indexing start from zeroth index
print(arr[0][1])
print(arr[1:,2:])
print(arr[0:2,2:])

2
[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]


In [18]:
##modify the array element 
arr[0,0] =100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [19]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [21]:
##statical concept--Normalization
# to have mean of 0 and standard deviations of 1 
data = np.array([1,2,3,4,5])
##calculate the mean and standard deviations
mean = np.mean(data)
std_dev = np.std(data)
##normalize the data 
normalized_data = (data - mean) /std_dev
print("normaized data ",normalized_data)

normaized data  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [22]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
##mean is 
mean = np.mean(data)
print("Mean is", mean)
##median is 
median = np.median(data)
print("Median is ",median)
##Standard deviation is 
std_dev = np.std(data)
print("standard deviation is " ,std_dev)
##variance is 
variance = np.var(data)
print("variance is ",variance)

Mean is 5.5
Median is  5.5
standard deviation is  2.8722813232690143
variance is  8.25


In [30]:
#logical oprations 
data = np.array([1,2,3,4,5,6,7,8,9,10])
print(data>5)
data[data>5]
print(data[(data >=5) & (data<8)])

[False False False False False  True  True  True  True  True]
[5 6 7]


In [28]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data >=5) & (data<8)]

array([5, 6, 7])